

<Widgets>:
    Label:
        id: display_time
        text: root.countdown()
        color: 1,1,1,1
        pos: 350,400
        font_size: 80

    Button:
        size: 100, 75
        pos: 0, 0
        text: "Start"
        color: 0,1,0,1
        font_size: 40
        on_press: root.countdown()
    Button:
        size: 100, 75
        pos: 100, 0
        text: "Stop"
        color: 1,0,0,1
        font_size: 40